name: Makefile CI

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1
            - name: Run CodeBuild
              uses: aws-actions/aws-codebuild-run-build@v1
              with:
                  project-name: CodeBuild-devops-xincloud
                  image-override: doctrine/nodejs-aws-cli:latest
                  env-vars-for-codebuild: |
                      AWS_ACCESS_KEY_ID,
                      AWS_SECRET_ACCESS_KEY
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
